# Generated by Django 2.1.7 on 2019-03-05 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190305_0345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.IntegerField(default=1),
        ),
    ]
