# Generated by Django 2.1.7 on 2019-03-05 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190224_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年')], default=1),
        ),
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('BasketBall', 'BasketBall'), ('Tennis', 'Tennis'), ('TableTennis', 'TableTennis'), ('VolleyBall', 'VolleyBall')], default='Soccer', max_length=15),
        ),
    ]
