# Generated by Django 2.1.7 on 2019-03-05 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190305_0428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='grade',
            field=models.IntegerField(choices=[(1, '1年'), (2, '2年'), (3, '3年'), (4, '4年')], default=1),
        ),
    ]
