# Generated by Django 2.1.7 on 2019-03-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20190305_1349'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('BasketBall', 'BasketBall'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('TableTennis', 'TableTennis'), ('VolleyBall', 'VolleyBall')], default='Soccer', max_length=15),
        ),
    ]
