# Generated by Django 2.1.7 on 2019-03-11 10:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20190311_1046'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='event',
            field=models.CharField(choices=[('Soccer', 'Soccer'), ('BasketBall', 'BasketBall'), ('Tennis', 'Tennis'), ('Badminton', 'Badminton'), ('TableTennis', 'TableTennis'), ('VolleyBall', 'VolleyBall')], max_length=15),
        ),
    ]
