# Generated by Django 2.1.7 on 2019-03-11 11:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190311_1054'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='grade',
        ),
    ]
