version: '3'

services:
  djangoapp:
    build: .
    volumes:
      - .:/opt/services/djangoapp/src
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    networks:
      - nginx_network
      - database1_network
      - redis_server_network
      - worker_network
      - scheduler_network
    depends_on:
      - database1
      - redis_server

  nginx:
    image: nginx:1.13
    ports:
      - 8080:80
    volumes:
      - ./config/nginx/conf.d:/etc/nginx/conf.d
      - static_volume:/opt/services/djangoapp/static
      - media_volume:/opt/services/djangoapp/media
    depends_on:
      - djangoapp
    networks:
      - nginx_network
  
  database1:
    image: postgres:10
    env_file:
      - config/db/database1_env
    networks:
      - database1_network
    volumes:
      - database1_volume:/var/lib/postgresql/data
      
  redis_server:
    image: redis
    ports:
      - "6379:6379"
    networks:
      - redis_server_network
      - worker_network
      - scheduler_network
      - database1_network

  worker:
    build: .
    depends_on:
      - redis_server
    networks:
      - worker_network
      - database1_network
    working_dir: /opt/services/djangoapp/src/sportsfes
    command: python3 manage.py rqworker

  scheduler:
    build: .
    depends_on:
      - redis_server
    networks:
      - scheduler_network
      - database1_network
    working_dir: /opt/services/djangoapp/src/sportsfes
    command: python3 manage.py schedule
    

networks:
  nginx_network:
    driver: bridge
  database1_network:
    driver: bridge
  redis_server_network:
    driver: bridge
  worker_network:
    driver: bridge
  scheduler_network:
    driver: bridge

volumes:
  database1_volume:
  static_volume:
  media_volume:
