# Generated by Django 2.1.5 on 2019-02-06 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190204_0541'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='team',
            name='leader',
        ),
        migrations.RemoveField(
            model_name='member',
            name='team',
        ),
        migrations.AddField(
            model_name='member',
            name='number',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.DeleteModel(
            name='Team',
        ),
    ]
